# Generated by Django 5.2.6 on 2025-09-29 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0002_rename_roll_numder_registration_roll_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('qr_code', models.ImageField(upload_to='qr_codes/')),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registrations.registration')),
            ],
        ),
    ]
