# Generated by Django 5.2.6 on 2025-09-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryPass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrypass',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
