# Generated by Django 5.2.6 on 2025-09-29 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='roll_numder',
            new_name='roll_number',
        ),
    ]
